routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('movie', 'MovieController');
Route::get('movie/destroy/{id}', ['as'=> 'movie/destroy', 'uses' => 'MovieController@destroy']);
Route::post('movie/show', ['as' => 'movie/show', 'uses' => 'MovieController@show']);
Route::post('movie/update/{id}', ['as'=>'movie/update', 'uses'=>'MovieController@update']);

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $table = 'movies';
    protected $fillable = ['name', 'description'];
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Movie as Movie;

class MovieController extends Controller
{
    public function update($id, Request $request){
        $movie =Movie::find($id);
        $movie->name = $request->name;
        $movie->description = $request->description;
        $movie->save();
        return redirect('movie');
    }
    public function edit($id){
        $movie =Movie::find($id);
        return \View::make('movies/update', compact('movie'));
    }
    public function index()
    {
        $movies = Movie::all();
        return \View::make('movies/list',compact('movies'));
    }
	public function create()
	{
		return \View::make('movies/new');
	}
    public function store(Request $request)
    {
    	$movie = new Movie;
    	$movie->name = $request->name;
        $movie->description = $request->description;
        $movie->save();
    	return redirect('movie');
    }
    public function show(Request $request){
        $movies = Movie::where('name', 'like', '%'.$request->name.'%')->get();
        return \View::make('movies/list', compact('movies'));
    }
    public function destroy($id){
        $movie = Movie::find($id);
        $movie->delete();
        return redirect()->back();
    }
}

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				<form action="{{route('movie/show')}}" method="post" novalidate class="form-inline">
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" namme="name">
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{route('movie.index')}}" class="btn btn-primary">Todo</a>
						<a href="{{route('movie.create')}}" class="btn btn-primary">Crear</a>
					</div>
				</form>
			</article>
			<article class="col-md-12">
				<table class="table table-codensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Descricion</th>
							<th>Accion</th>
						</tr>
					</thead>
					<tbody>
						@foreach($movies as $movie)
						<tr>
							<td>{{$movie->name}}</td>
							<td>{{$movie->description}}</td>
							<td>
								<a class="btn btn-primary btn-xs" href="{{router('movie.edit',['id' => $movie->id]) }}">Editar</a>
								<a class="btn btn-danger btn-xs" href="{{router('movie/destroy',['id' => $movie->id]) }}">Eliminar</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection			

resources/views/movies/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				<form action="{{route('movie.store')}}" method="post" novalidate>
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Descripcion</label>
						<input type="text" name="description" class="form-control" required>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-succes">Enviar</button>
					</div>
				</form>
			</article>
		</div>
	</section>
@endsection

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				<form action="{{route('movie/update', ['id'=> $movie->id])}}" method="post" novalidate>
					@csrf
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required value="{{$movie->name}}">
					</div>
					<div class="form-group">
						<label>Descripcion</label>
						<input type="text" name="description" class="form-control" required value="{{$movie->description}}">
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-succes">Enviar</button>
					</div>
				</form>
			</article>
		</div>
	</section>
@endsection